language: java

jdk:
  - openjdk14

sudo: false

install: true
script: mvn clean package -DskipTests=true
services:
  - postgresql

before_install:
  - psql -c "CREATE DATABASE grabber_db;" -U postgres

env:
  global:

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - zubovvp@yandex.ru
    on_success: never
    on_failure: always
