language: java

jdk:
  - openjdk14

sudo: false

install: true
script:
  - mvn install
services:
  - postgresql

before_install:
  - psql -c "CREATE DATABASE grabber_db;" -U postgres

env:
  global:
    - CODECOV_TOKEN="c1fa9a7f-05b8-4ba5-a05c-606979e3758d"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - zubovvp@yandex.ru
    on_success: never
    on_failure: always
